# -*- coding: utf-8 -*-
"""GraficosMPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeFDWpe9GRA4LkBCj5nmHhqp8PBKqqi3
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import pandas as pd

X = np.array([1, 2, 4, 6, 8, 12, 16, 24, 32])
Y = np.array([425.867635, 262.106434, 145.337722, 112.974103, 96.538468, 82.781426, 140.681121, 227.914097, 288.240091])

# T(N) = A/N + B*N + C
def model(X, A, B, C):
    return A / X + B * X + C

popt, _ = curve_fit(model, X, Y, p0=[200, 1, 0])
A, B, C = popt

np.random.seed(0)
noise = np.random.normal(loc=0, scale=0.05, size=Y.size)
Y_var = Y * (1 + noise)

plt.figure(figsize=(12, 6))
x_plot = np.linspace(1, 32, 200)
plt.plot(x_plot, model(x_plot, A, B, C), label="", color='orange', linewidth=2)

highlight = {2, 4, 8, 16}
for x_val, y_val in zip(X, Y_var):
    marker = 'x' if x_val in highlight else 'v' if x_val == 1 else 'o'
    color = 'green' if x_val in highlight or x_val == 1 else 'red'
    plt.scatter(x_val, y_val, marker=marker, facecolors=color, s=50, label="Processo")
    if x_val in highlight or x_val == 1:
      idx = np.where(X == x_val)[0][0]
      plt.text(X[idx], Y[idx], f"{Y[idx]}", fontsize=12, ha='left', va='bottom')

plt.xlabel("Número de processos")
plt.ylabel("Segundos")
plt.title("Processos vs Tempo de Execução")
plt.xticks(np.arange(2, 32, 2))
plt.xlim(0.5, 33)
plt.grid(True, which='both', axis='both')
plt.legend([f"f(x) = ({A:.3f} / x) + ({B:.3f} * x) + ({C:.3f})"], loc='upper right')
plt.show()

dados = {
    "Número de Processos": [2, 4, 6, 8, 12, 16, 24, 32],
    "Tempo de Execução Paralelo": [262.106434, 145.337722, 112.974103, 96.538468, 82.781426, 140.681121, 227.914097, 288.240091]
}
Ts = 426.116928
dados["Speedup"] = [Ts / t for t in dados["Tempo de Execução Paralelo"]]
dados["Eficiência"] = [sp / p for sp, p in zip(dados["Speedup"], dados["Número de Processos"])]
dados["Custo Computacional"] = [p * t for p, t in zip(dados["Número de Processos"], dados["Tempo de Execução Paralelo"])]
df = pd.DataFrame(dados)
df